### ISSUE TITLE
Form Handling - Database Schema Design for Questions and Responses

### ISSUE THREAD

**Issue by RuntaoZhuge** [PTE-Score-Analysis/serverless-api#11]
### Task Description
- Design database tables for storing predefined questions and user responses.
- Include fields, data types, and relationships in the design.

### Acceptance Criteria
- Database schema for questions and responses is well-defined and documented.

**Comment by chang019** [comment]
I have a question about this design:
if a student submits 2 forms on 1 date. Can we distinguish different forms' answers (when we need to render the info by form in pages like 'submission history')?

**Comment by RuntaoZhuge** [comment]
I think you only need to focus on building the one for questions and answers. Basically, our predefined questions can be in one table and the user responses can be in another one. If a user uploaded two then we just need to get both of them and render them. Typically, I don't think we would use the data for rendering, and even if we have to render it we can just use their ids should be fine. We will only use the questions for analysis and each analysis will likely to have only one survey attached. Because of the nature of Postgres, I think the best way would be we treat the response like metadata and store it as json, so we can store in a {question:answer} format json. 
```
{
"How many times have you taken PTE": 3,
 "What is your target score": 66
}
```

Also, please notice that we probably won't render their answers to the app but we do need to link the user info to the answer table. To maximize the performance, I think the best way would be to make a table with user_id stored as a constraint so we can link them  

Because one user can have multiple scores, so having a separate table saying examScore and Listening score and linke them would be a bit undirect as you have to connect to a second table to get the score, instead I think a better way is to have a seperate table called past_exam_score and store the user_id and data there so in this way we can have multiple users and each user can have multiple tests results. Also need to remember that we will also store the PDF documents and my suggestion is that we store the link to the S3 or the name of the file, I personally think grab the link should be more staightforward

One thing I want to put on here is that you might want to talk to @FENGNUM  regarding to the user table design and also Frank since the cognito would also store part of the info that our db has, and user table is part of @FENGNUM job as well.

Good job on the graph but we need to dig a bit more. Feel free to create it in you local db and it would be more staightforward when you have a visualized table actually works.
