### ISSUE TITLE
Authentication Integration - AWS Cognito and WeChat Setup

### ISSUE THREAD

**Issue by RuntaoZhuge** [PTE-Score-Analysis/serverless-api#5]
- Research and document the process for integrating AWS Cognito.
- Research and document the process for integrating with WeChat. 
- Set up a basic AWS Cognito user pool.

### Acceptance Criteria
- A document detailing the integration process is created.
- A user pool in AWS Cognito is successfully set up and ready for integration.

**Comment by FrankQian1993** [comment]
Had some questions need to discuss about the user pool creating on AWS. currently was stuck in Configure message delivery.

The following are the questions and the screenshots of the creating progress.

[Userpoolcreate.docx](https://github.com/PTE-Score-Analysis/serverless-api/files/13483311/Userpoolcreate.docx)

For the integrating AWS Cognito:
https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-integrate-apps.html
The information here might help solve the problem.

For Wechat mini program, I did some research and not sure whether this is what we want or not, please see the following link:
https://developers.weixin.qq.com/miniprogram/dev/framework/open-ability/login.html

If you are available tonight hope we can discuss on discord to go through the ticket.
Thanks

**Comment by RuntaoZhuge** [comment]
The approach should be pretty much in this way. We would likely to use only a few of cognito sign-ins but mostly wechat, so I believe we would need to dig into the wechat auth a bit more
