### ISSUE TITLE
Image Upload - Lambda Function for File Upload

### ISSUE THREAD

**Issue by RuntaoZhuge** [PTE-Score-Analysis/serverless-api#9]
### Task Description
- Develop a Lambda function to handle image uploads.
- Implement file type and size validation.

### Acceptance Criteria
- Lambda function can securely receive and store images in S3.
- File type and size validation is implemented.

**Comment by JingH18** [comment]
I am doing research on working with AWS Lambda functions today.

**Comment by JingH18** [comment]
Since we changed our minds to upload images, not PDFs, this issue should be fixed.

**Comment by RuntaoZhuge** [comment]
This should be changed to upload images. The function should be the same
